### ISSUE TITLE
[BUG] An issue with h5py

### ISSUE THREAD

**Issue by vvp-nsk** [linusjoonho/ipie#198]
**Describe the bug**
I am trying to install IPIE v0.6.2 on a new machine. The compilation went smoothly. However, there is a problem with running example-01. Specifically, it fails with the following error message:

```
# Available memory on the node is 0.000 GB
Traceback (most recent call last):
  File "/cfs/klemming/home/v/vivy/Private/Devel/ipie/bin/ipie", line 4, in <module>
    __import__('pkg_resources').run_script('ipie==0.6.2', 'ipie')
  File "/pdc/software/21.11/eb/software/Anaconda3/2021.05/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/pdc/software/21.11/eb/software/Anaconda3/2021.05/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/cfs/klemming/home/v/vivy/Private/Devel/ipie/lib/python3.8/site-packages/ipie-0.6.2-py3.8-linux-x86_64.egg/EGG-INFO/scripts/ipie", line 82, in <module>
    main(sys.argv[1])
  File "/cfs/klemming/home/v/vivy/Private/Devel/ipie/lib/python3.8/site-packages/ipie-0.6.2-py3.8-linux-x86_64.egg/EGG-INFO/scripts/ipie", line 77, in main
    afqmc.run(comm=comm, verbose=True)
  File "/cfs/klemming/home/v/vivy/Private/Devel/ipie/lib/python3.8/site-packages/ipie-0.6.2-py3.8-linux-x86_64.egg/ipie/qmc/afqmc_batch.py", line 358, in run
    self.estimators.initialize(comm)
  File "/cfs/klemming/home/v/vivy/Private/Devel/ipie/lib/python3.8/site-packages/ipie-0.6.2-py3.8-linux-x86_64.egg/ipie/estimators/handler.py", line 185, in initialize
    fh5['block_size_1/walker_prop_header'] = self.walker_header
  File "/pdc/software/21.11/eb/software/Anaconda3/2021.05/lib/python3.8/site-packages/h5py/_hl/group.py", line 387, in __setitem__
    ds = self.create_dataset(None, data=obj, dtype=base.guess_dtype(obj))
  File "/pdc/software/21.11/eb/software/Anaconda3/2021.05/lib/python3.8/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/pdc/software/21.11/eb/software/Anaconda3/2021.05/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py/h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1717, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U12')
```

Could you please advise me on what could be wrong with my local installation?

Thank you in advance!

With best regards, 
Victor

**Other information:**
```
# Initialising pie simulation from input.json
# Setting batched to True.
# ipie version: 0.6.2
# Git hash: 47f06be051684341ceff132694a2675c1e1e08c5.
# Git branch: develop.
# Calculation uuid: 657634dc-9728-11ed-8792-95db50a34d04.
# Approximate memory available per node: 251.3201 GB.
# Running on 1 MPI rank.
# Root processor name: nid001159
# Python interpreter: 3.8.8 (default, Apr 13 2021, 19:58:26)  [GCC 7.3.0]
# Using numpy v1.20.1 from: /pdc/software/21.11/eb/software/Anaconda3/2021.05/lib/python3.8/site-packages/numpy.
# - BLAS lib: mkl_rt pthread
# - BLAS dir: /pdc/software/21.11/eb/software/Anaconda3/2021.05/lib
# Using scipy v1.6.2 from: /pdc/software/21.11/eb/software/Anaconda3/2021.05/lib/python3.8/site-packages/scipy.
# Using h5py v2.10.0 from: /pdc/software/21.11/eb/software/Anaconda3/2021.05/lib/python3.8/site-packages/h5py.
# Using mpi4py v3.1.3 from: /pdc/software/21.11/other/mpi4py/gnu/3.1.3-py38/lib/python3.8/site-packages/mpi4py.
# - mpicc: /opt/cray/pe/craype/2.7.12/bin/cc
# Package cupy not found.
# MPIHandler detected 1 groups with 1 members each
# Parsing input options for systems.Generic.
# Number of alpha electrons: 5
# Number of beta electrons: 5
# Have shared memory: True
# Time to read integrals: 0.004718
# Note: symmetry not specified. Setting to default value of True.
# Time to pack Cholesky vectors: 0.000159
# Parsing input options for hamiltonians.Generic.
# Found real Choleksy integrals.
# Number of orbitals: 10
# Approximate memory required by Cholesky vectors 0.000020 GB
# Number of Cholesky vectors: 27
# Number of fields: 27
# Finished setting up hamiltonians.Generic object.
# Approximate memory required by packed Cholesky vectors 0.000011 GB
# Setting num_walkers to 640.
# Note: num_walkers not specified. Setting to default value of None.
# Setting timestep to 0.005.
# Setting batched to True.
# Setting num_steps to 25.
# Setting blocks to 10.
# Setting stabilise_freq to 5.
# Setting pop_control_freq to 5.
# Note: equilibration_time not specified. Setting to default value of 2.0.
# Note: rng_seed not specified. Setting to default value of None.
# random seed is 13658611
# Building trial wavefunction object.
# Setting filename to wavefunction.h5.
# Reading wavefunction from wavefunction.h5.
# Number of determinants in trial wavefunction: 1
# Parsing input options for trial_wavefunction.MultiSlater.
# Note: wicks not specified. Setting to default value of False.
# Note: optimized not specified. Setting to default value of True.
# Note: use_wicks_helper not specified. Setting to default value of False.
# Note: ndets not specified. Setting to default value of 1.
# Note: compute_trial_energy not specified. Setting to default value of True.
# Assuming non-orthogonal trial wavefunction expansion.
# Trial wavefunction shape: (1, 10, 10)
# Using initial wavefunction from file.
# Note: ndets_for_trial_props not specified. Setting to default value of 1.
# Note: ndet_chunks not specified. Setting to default value of 1.
# Finished setting up trial_wavefunction.MultiSlater.
# Constructing half rotated Cholesky vectors.
# Shape of alpha half-rotated Cholesky: (27, 50)
# Shape of beta half-rotated Cholesky: (27, 50)
# Only performing half-rotation of the reference determinant
# Half-Rotating Cholesky for determinant.
# Memory required by half-rotated integrals:  0.0000 GB.
# Time to half-rotated integrals: 0.19114160537719727 s.
# Note: recompute_ci not specified. Setting to default value of False.
# Note: spin_proj not specified. Setting to default value of None.
# Note: init_walker not specified. Setting to default value of None.
# Computing trial wavefunction energy.
# (E, E1B, E2B): (-5.25628129e+00, -1.68063463e+01, 1.15500650e+01)
# Time to evaluate local energy: 1.0577082633972168 s
# Trial wfn energy is (-5.256281292489259+0j)
# Getting propagator driver
# Parsing input options for propagation.Continuous.
# Using continuous Hubbard--Stratonovich transformations.
# Using phaseless approximation: True
# Setting force bias to True.
# Time to mean field shift: 8.893013000488281e-05 s
# Absolute value of maximum component of mean field shift: 2.88642458e+00.
# Finished setting up propagation.GenericContinuous.
# Using hybrid weight update.
# Using phaseless approximation.
# Getting WalkerBatchHandler
# Setting up walkers.handler_batch.Walkers.
# qmc.nwalkers = 640
# qmc.ntot_walkers = 640
# Using single det walker with a single det trial.
# Note: population_control not specified. Setting to default value of pair_branch.
# Using pair_branch population control algorithm.
# Buffer size for communication: 1.59442425e-06 GB
# Finish setting up walkers.handler.Walkers.
# Setting up estimator object.
# Note: index not specified. Setting to default value of 0.
# Setting filename to estimates.0.h5.
# Note: basename not specified. Setting to default value of estimates.
# Writing estimator data to estimates.0.h5.
# Note: buffer_size not specified. Setting to default value of 1000.
# Note: observables not specified. Setting to default value of {'energy': {}}.
# Finished settting up estimator object.
# NOTE: cupy available but qmc.gpu == False.
#       If this is unintended set gpu option in qmc  section.
# Available memory on the node is 0.000 GB
```

**Comment by fdmalone** [comment]
Thanks for reporting. It's a silly bug (on our part) with trying to write a string to HDF5. I'll push a fix shortly.

**Comment by vvp-nsk** [comment]
Hi!

I will be waiting for a fix. 

Thank you!

With best regards, 
Victor

**Comment by fdmalone** [comment]
The issue is your h5py version is too low. I've bumped the minimum version to 3.0.0 in the requirements.txt.
